#!/usr/bin/env bash
# Clone this persona-memory project into a fresh directory configured for a
# new persona. Each persona owns its own directory, CLAUDE.md, .mcp.json,
# and DB — matching the design "1 親エージェント = 1 プロジェクト = 1 記憶
# = 1 個性 (ペルソナ)".
#
# Usage:   scripts/new-persona.sh <persona-name> <target-dir>
# Example: scripts/new-persona.sh satoshi ~/Desktop/claude_dev/satoshi
#
# After this script finishes:
#   cd <target-dir> && claude
set -euo pipefail

PERSONA="${1:-}"
TARGET="${2:-}"

if [[ -z "$PERSONA" || -z "$TARGET" ]]; then
  echo "Usage: $0 <persona-name> <target-dir>" >&2
  echo "Example: $0 satoshi ~/Desktop/claude_dev/satoshi" >&2
  exit 1
fi

if [[ -e "$TARGET" ]]; then
  echo "Target already exists: $TARGET" >&2
  exit 1
fi

SOURCE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! command -v rsync >/dev/null 2>&1; then
  echo "rsync is required but not found in PATH" >&2
  exit 2
fi

log() { printf '\033[36m[new-persona]\033[0m %s\n' "$*"; }

log "cloning $SOURCE -> $TARGET (persona: $PERSONA)"
mkdir -p "$TARGET"
TARGET_ABS="$(cd "$TARGET" && pwd)"

# Copy template files; skip volatile, per-persona, and host-specific artifacts.
rsync -a \
  --exclude='.git/' \
  --exclude='data/' \
  --exclude='.venv/' \
  --exclude='__pycache__/' \
  --exclude='*.pyc' \
  "$SOURCE/" "$TARGET_ABS/"

# Generate .mcp.json from the template (source's .mcp.json is gitignored, so
# rsync may not have copied one). The template still uses {{ROOT}}/{{PERSONA}}/
# {{LIGHT_MODEL}}/{{HEAVY_MODEL}}/{{EMBED_MODEL}} placeholders.
python3 - "$TARGET_ABS" "$PERSONA" <<'PY'
import os, pathlib, sys
target, persona = sys.argv[1], sys.argv[2]
template = pathlib.Path(target) / ".mcp.json.template"
out = pathlib.Path(target) / ".mcp.json"
light = os.environ.get("PERSONA_LIGHT_MODEL", "gemma3:4b")
heavy = os.environ.get("PERSONA_HEAVY_MODEL", "gemma3:12b")
embed = os.environ.get("PERSONA_EMBED_MODEL", "nomic-embed-text")
content = (
    template.read_text()
    .replace("{{ROOT}}", target)
    .replace("{{PERSONA}}", persona)
    .replace("{{LIGHT_MODEL}}", light)
    .replace("{{HEAVY_MODEL}}", heavy)
    .replace("{{JUDGE_MODEL}}", light)  # back-compat
    .replace("{{EMBED_MODEL}}", embed)
)
out.write_text(content)
PY
log "generated .mcp.json -> data/$PERSONA.db"

# Tag CLAUDE.md with the persona name in the title.
python3 - "$TARGET_ABS" "$PERSONA" <<'PY'
import re, pathlib, sys
target, persona = sys.argv[1], sys.argv[2]
p = pathlib.Path(target) / "CLAUDE.md"
content = p.read_text()
content = re.sub(
    r"^# persona-memory.*\n",
    f"# persona-memory: {persona}\n",
    content,
    count=1,
)
p.write_text(content)
PY
log "tagged CLAUDE.md title with persona name"

# Bootstrap venv + Ollama models + DB.
cd "$TARGET_ABS"
./setup.sh "$PERSONA"

# Write per-persona config.env (sourced by hook scripts via load_persona_env.sh)
# and the active-persona pointer so hooks pick this DB on first launch.
LIGHT="${PERSONA_LIGHT_MODEL:-gemma3:4b}"
HEAVY="${PERSONA_HEAVY_MODEL:-gemma3:12b}"
EMBED="${PERSONA_EMBED_MODEL:-nomic-embed-text}"
mkdir -p "$TARGET_ABS/data"
cat > "$TARGET_ABS/data/$PERSONA.config.env" <<CONFIG_EOF
# Generated by new-persona.sh on $(date '+%Y-%m-%d %H:%M:%S')
PERSONA_MEMORY_DB="$TARGET_ABS/data/$PERSONA.db"
PERSONA_LIGHT_MODEL="$LIGHT"
PERSONA_HEAVY_MODEL="$HEAVY"
PERSONA_EMBED_MODEL="$EMBED"
OLLAMA_HOST="http://localhost:11434"
CONFIG_EOF
echo "$PERSONA" > "$TARGET_ABS/data/active-persona"
log "wrote data/$PERSONA.config.env + data/active-persona"

cat <<EOF

==========================================================================
Persona created: $PERSONA
  Directory:    $TARGET_ABS
  DB:           $TARGET_ABS/data/$PERSONA.db
  MCP config:   $TARGET_ABS/.mcp.json
  config.env:   $TARGET_ABS/data/$PERSONA.config.env
  active flag:  $TARGET_ABS/data/active-persona  -> $PERSONA
  light model:  $LIGHT  (write side)
  heavy model:  $HEAVY  (read-side compression)

Next steps:
  cd "$TARGET_ABS"

  # (A) インタラクティブな性格セットアップを行う:
  scripts/init.sh
  # → 9 質問で役割・性格・口調・名前等を seed (推奨)

  # (B) 空のペルソナのまま会話で覚えさせる:
  claude
  # → 最初は persona facts なし。会話で振る舞い指示を与えると auto_persist が
  #    write_fact("persona", ...) で蓄積、次回 SessionStart から注入される。
==========================================================================
EOF
